name: Run RMarkdown Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_rmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2'

    - name: Set up system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install pandoc
      run: |
        sudo apt-get install -y pandoc

    - name: Install 'tseries' package
      run: |
        Rscript -e "install.packages('tseries', repos='http://cran.rstudio.com/', dependencies=TRUE)"

    - name: Install 'tseries' package if missing
      run: |
        Rscript -e "if(!require('tseries')) install.packages('tseries', repos='http://cran.rstudio.com/')"

    - name: Install required R packages
      run: |
        Rscript -e "install.packages(c('rmarkdown', 'forecast', 'ggfortify', 'readxl', 'xts', 'randomForest'), repos='http://cran.rstudio.com/', dependencies=TRUE)"

    - name: Install forecast package using remotes
      run: |
        script -e "if(!require('forecast')) remotes::install_cran('forecast')"     

    - name: Render RMarkdown document
      run: |
        Rscript -e "rmarkdown::render('TimeSeries_script.Rmd')"

    - name: Upload pdf output
      uses: actions/upload-artifact@v3
      with:
        name: rmd-output
        path: TimeSeries_script.pdf
