name: Run RMarkdown Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_rmd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2'

    - name: Install pandoc
      run: |
        sudo apt-get install -y pandoc

    - name: Install required R packages
      run: |
        Rscript -e "install.packages(c('rmarkdown', 'forecast', 'ggfortify', 'readxl', 'xts', 'randomForest'), repos='http://cran.rstudio.com/', dependencies=TRUE)"

    - name: Render RMarkdown document
      run: |
        Rscript -e "rmarkdown::render('TimeSeries_script.Rmd')"

    - name: Upload pdf output
      uses: actions/upload-artifact@v3
      with:
        name: rmd-output
        path: TimeSeries_script.pdf
